use_frameworks!

target 'TXJAllTools_Example' do
  pod 'TXJAllTools', :path => '../'

  target 'TXJAllTools_Tests' do
    inherit! :search_paths
	pod 'FLEX', '~> 2.4.0'
    #pod 'AFNetworking'
  end
end
