use_frameworks!

target 'TXJAllTools_Example' do
  pod 'TXJAllTools', :path => '../'
  pod 'FLEX', '~> 2.4.0'
  pod 'GBDeviceInfo', '~> 5.2.0'
  pod 'ReactiveObjC', '~> 3.1.0' #点击事件
  target 'TXJAllTools_Tests' do
    inherit! :search_paths
	
    #pod 'AFNetworking'
    pod 'Masonry'
    
  end
end
